### ISSUE TITLE
wrong-type-argument consp nil

### ISSUE THREAD

**Issue by noctuid** [alphapapa/matrix-client.el#99] opened 2020-05-01 02:13 UTC
`matrix-client-connect` fails for me. Looks like it is some issue with the avatar.
```
Debugger entered--Lisp error: (wrong-type-argument consp nil)
  image--set-property(nil :max-width 35)
  matrix--room-display-name(#<matrix-room matrix-room-156b9a201760>)
```

**Comment by alphapapa** [comment] 2020-05-01 11:04
That's not much for me to go on.  If you can reproduce it, try using `matrix-log` to find the room and avatar that you think are causing the problem.

Note that `matrix-client-connect` is asynchronous, and it's already returned by that point; what's probably failing is in the initial sync callback's event-processing loop.

**Comment by noctuid** [comment] 2020-05-01 13:49
Looks like it succeeds for riot-bot and the freenode irc bridge and then fails for `#tridactyl`. This happens consistently for me and also happens if I remove it as a room and then try to join it. It doesn't happen for other rooms, so maybe you can replicate it.

**Comment by alphapapa** [comment] 2020-05-02 00:58
`#tridactyl` is not a complete Matrix room address, so I don't know what room you mean.

Please look into the room avatar.  Is the URL actually downloadable?  Is there anything weird about the image?  etc.

**Comment by noctuid** [comment] 2020-05-02 02:13
> #tridactyl is not a complete Matrix room address, so I don't know what room you mean.

[#tridactyl:matrix.org](https://riot.im/app/#/room/#tridactyl:matrix.org) doesn't work for you?

> Is the URL actually downloadable?

[Yes](https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/hrEeBCczozcwsFGSLGVoqBwA?width=96&height=96&method=crop)

> Is there anything weird about the image?

Not as far as I can tell.

**Comment by alphapapa** [comment] 2020-05-02 15:28
> > #tridactyl is not a complete Matrix room address, so I don't know what room you mean.
> 
> [#tridactyl:matrix.org](https://riot.im/app/#/room/#tridactyl:matrix.org) doesn't work for you?

It wasn't a full room alias, so I didn't know if you meant a Matrix room or a bridged Freenode channel.

> 
> > Is the URL actually downloadable?
> 
> [Yes](https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/hrEeBCczozcwsFGSLGVoqBwA?width=96&height=96&method=crop)

`https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/hrEeBCczozcwsFGSLGVoqBwA?width=96&height=96&method=crop`

Please check the event log and see if the avatar URL in the room state data includes the HTTP query parameters, or if that part comes from Riot.  I don't know if that is the problem, but it's worth checking.

**Comment by seblemaguer** [comment] 2020-05-29 19:40
Hello,

I am facing this issue as well with all the rooms I have (emacs, org-mode and matrix-client).  I am going to investigate this a little bit more during the week end.

**Comment by seblemaguer** [comment] 2020-06-07 17:56
so, so far it seems that when the callback `matrix-client-room-avatar-callback` the argument `data` is nil which triggers the avatar field to be set to `" " ` instead of nil.

**Comment by alphapapa** [comment] 2020-06-10 01:04
@seblemaguer Can you check HTTP query parameters as I mentioned?

> I am facing this issue as well with all the rooms I have (emacs, org-mode and matrix-client).

I just started the client, and I'm in all of those rooms, and they're all working fine for me.

**Comment by seblemaguer** [comment] 2020-06-10 07:47
@alphapapa In the event log the keyword avatar is not appearing once. I didn't have time to go further since last time but I will give it a look tonight.

**Comment by seblemaguer** [comment] 2020-07-08 08:08
Ok I think I spotted something. I don't have emacs with imagemagick support. The following line is actually not validated which leads the function to return nil:

https://github.com/alphapapa/matrix-client.el/blob/59c792423fd0503f1375f356bec56130e65d3b51/matrix-client-images.el#L73

@noctuid could you please check if that is also the case on your side?

@alphapapa I prepare a patch to have matrix not fail even if imagemagick is not available

**Comment by alphapapa** [comment] 2023-03-14 10:23
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.

**Closed by alphapapa** 2023-03-14 10:23 UTC
Labels: bug
