### ISSUE TITLE
error in process filter: Wrong type argument: (or eieio-object class), nil, obj

### ISSUE THREAD

**Issue by seanfarley** [alphapapa/matrix-client.el#100] opened 2020-06-14 20:06 UTC
Not sure if this will help or not because I have no idea what's going on:

(I removed some private data about my list of contacts but if that data is needed, I can send privately)

```
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  #f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x4043c3ed>)(nil tags)
  eieio-oref--closql-oref(#f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x4043c3ed>) nil tags)
  apply(eieio-oref--closql-oref #f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x4043c3ed>) (nil tags))
  eieio-oref(nil tags)
  matrix-client-room-buffer-priority<(#<buffer smf (IRC)> #<killed buffer>)
  [...]
  matrix-client-frame-update-sidebar(#<matrix-session matrix-session>)
  run-hook-with-args(matrix-client-frame-update-sidebar #<matrix-session matrix-session>)
  matrix-sync-callback(#<matrix-session matrix-session> :cbargs nil :status (:peer (:certificate (:version 3 :serial-number "03:a8:15:1c:78:8b:03:27:cf:5f:38:96:b8:de:e8:37:52:fb" :issuer "C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3" :valid-from "2020-06-05" :valid-to "2020-09-03" :subject "CN=*.farley.io" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:b7:59:c9:98:1d:b3:37:a9:a2:12:48:db:55:50:59:f9:ec:74:7a:52" :certificate-id "sha1:03:94:e2:ef:ff:62:03:99:e2:78:61:1b:06:a4:18:07:a3:c9:d2:fc") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD")) :headers "HTTP/1.1 200 OK\nServer: nginx\nDate: Sun, 14 Jun 2020 20:01:58 GMT\nContent-Type: application/json\nTransfer-Encoding: chunked\nConnection: close\nCache-Control: no-cache, no-store, must-revalidate\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nContent-Encoding: gzip\n" :data ((account_data (events . [])) (to_device (events . [])) (device_lists (changed . []) (left . [])) (presence (events . [])) (rooms (join) (invite) (leave)) (groups (join) (invite) (leave)) (device_one_time_keys_count) (next_batch . "s3262_306597_190_2379_140_2_218_1296_1763")))
  apply(matrix-sync-callback (#<matrix-session matrix-session> :cbargs nil :status (:peer (:certificate (:version 3 :serial-number "03:a8:15:1c:78:8b:03:27:cf:5f:38:96:b8:de:e8:37:52:fb" :issuer "C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3" :valid-from "2020-06-05" :valid-to "2020-09-03" :subject "CN=*.farley.io" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:b7:59:c9:98:1d:b3:37:a9:a2:12:48:db:55:50:59:f9:ec:74:7a:52" :certificate-id "sha1:03:94:e2:ef:ff:62:03:99:e2:78:61:1b:06:a4:18:07:a3:c9:d2:fc") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD")) :headers "HTTP/1.1 200 OK\nServer: nginx\nDate: Sun, 14 Jun 2020 20:01:58 GMT\nContent-Type: application/json\nTransfer-Encoding: chunked\nConnection: close\nCache-Control: no-cache, no-store, must-revalidate\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nContent-Encoding: gzip\n" :data ((account_data (events . [])) (to_device (events . [])) (device_lists (changed . []) (left . [])) (presence (events . [])) (rooms (join) (invite) (leave)) (groups (join) (invite) (leave)) (device_one_time_keys_count) (next_batch . "s3262_306597_190_2379_140_2_218_1296_1763"))))
  #f(compiled-function (&rest args2) #<bytecode 0x44df0abd>)(:cbargs nil :status (:peer (:certificate (:version 3 :serial-number "03:a8:15:1c:78:8b:03:27:cf:5f:38:96:b8:de:e8:37:52:fb" :issuer "C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3" :valid-from "2020-06-05" :valid-to "2020-09-03" :subject "CN=*.farley.io" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:b7:59:c9:98:1d:b3:37:a9:a2:12:48:db:55:50:59:f9:ec:74:7a:52" :certificate-id "sha1:03:94:e2:ef:ff:62:03:99:e2:78:61:1b:06:a4:18:07:a3:c9:d2:fc") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD")) :headers "HTTP/1.1 200 OK\nServer: nginx\nDate: Sun, 14 Jun 2020 20:01:58 GMT\nContent-Type: application/json\nTransfer-Encoding: chunked\nConnection: close\nCache-Control: no-cache, no-store, must-revalidate\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nContent-Encoding: gzip\n" :data ((account_data (events . [])) (to_device (events . [])) (device_lists (changed . []) (left . [])) (presence (events . [])) (rooms (join) (invite) (leave)) (groups (join) (invite) (leave)) (device_one_time_keys_count) (next_batch . "s3262_306597_190_2379_140_2_218_1296_1763")))
  #f(compiled-function (url parser success-body-fn error-body-fn status cbargs) #<bytecode 0x40ba1e8d>)(("https://matrix.farley.io/_matrix/client/r0/sync?since=s3262_306559_190_2379_140_2_218_1296_1763&timeout=30000") json-read #f(compiled-function (&rest args2) #<bytecode 0x44df0abd>) #f(compiled-function (&rest args2) #<bytecode 0x44df0add>) (:peer (:certificate (:version 3 :serial-number "03:a8:15:1c:78:8b:03:27:cf:5f:38:96:b8:de:e8:37:52:fb" :issuer "C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3" :valid-from "2020-06-05" :valid-to "2020-09-03" :subject "CN=*.farley.io" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:b7:59:c9:98:1d:b3:37:a9:a2:12:48:db:55:50:59:f9:ec:74:7a:52" :certificate-id "sha1:03:94:e2:ef:ff:62:03:99:e2:78:61:1b:06:a4:18:07:a3:c9:d2:fc") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD")) nil)
  #f(compiled-function (status &optional cbargs) #<bytecode 0x44df0b0d>)((:peer (:certificate (:version 3 :serial-number "03:a8:15:1c:78:8b:03:27:cf:5f:38:96:b8:de:e8:37:52:fb" :issuer "C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3" :valid-from "2020-06-05" :valid-to "2020-09-03" :subject "CN=*.farley.io" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:b7:59:c9:98:1d:b3:37:a9:a2:12:48:db:55:50:59:f9:ec:74:7a:52" :certificate-id "sha1:03:94:e2:ef:ff:62:03:99:e2:78:61:1b:06:a4:18:07:a3:c9:d2:fc") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD")))
  apply(#f(compiled-function (status &optional cbargs) #<bytecode 0x44df0b0d>) (:peer (:certificate (:version 3 :serial-number "03:a8:15:1c:78:8b:03:27:cf:5f:38:96:b8:de:e8:37:52:fb" :issuer "C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3" :valid-from "2020-06-05" :valid-to "2020-09-03" :subject "CN=*.farley.io" :public-key-algorithm "RSA" :certificate-security-level "Medium" :signature-algorithm "RSA-SHA256" :public-key-id "sha1:b7:59:c9:98:1d:b3:37:a9:a2:12:48:db:55:50:59:f9:ec:74:7a:52" :certificate-id "sha1:03:94:e2:ef:ff:62:03:99:e2:78:61:1b:06:a4:18:07:a3:c9:d2:fc") :key-exchange "ECDHE-RSA" :protocol "TLS1.3" :cipher "AES-256-GCM" :mac "AEAD")))
  url-http-activate-callback()
  url-http-chunked-encoding-after-change-function(402 607 205)
  url-http-wait-for-headers-change-function(1 619 618)
  url-http-generic-filter(#<process matrix.farley.io<6>> "HTTP/1.1 200 OK\015\nServer: nginx\015\nDate: Sun, 14 Jun 2020 20:01:58 GMT\015\nContent-Type: application/json\015\nTransfer-Encoding: chunked\015\nConnection: close\015\nCache-Control: no-cache, no-store, must-revalidate\015\nAccess-Control-Allow-Origin: *\015\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\015\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\015\nContent-Encoding: gzip\015\n\015\nc1\015\n\037\213\010\0\0\0\0\0\004\003\225\217\301\016\2020\020D\177\205\364\354\201\026\005\361W\214\331\324\262B\025ZB\027\242!\374\273mQO\\\274\315\354d\366\355\316L*eGCPI\222\354\224\314\f'4\344\274<_\226]\302\310B\205\223V\270\025\256\011\264\332\305\306\314T#M\215Ul\373r\2137\372m\352\007th\266\027\015\326v\2019\263\273\325&\210\300\326f\322\024\301\301\265(\247\325\004W\017v\354\377\253|\256\265\006\201t\207\360\300\227\203\370\375\027h\360Ip\225\244\032?a.\023\271\200,\315\017e\001\274LAdE\011|\357\005\010~\004.\312\034x\221gly\003f\226\233\317H\001\0\0\015\n0\015\n\015\n")
```

**Comment by alphapapa** [comment] 2020-06-15 05:22
The problem may be here:
```
matrix-client-room-buffer-priority<(#<buffer smf (IRC)> #<killed buffer>)
```
It's strange that it's trying to compare one room's buffer with a killed buffer.  A killed buffer suggests that a room was joined and left.  That makes me wonder if the server is still sending the `join` event for that room on initial sync, after the event saying the room was left, which then ends up trying to compare a joined room's buffer with the left room's buffer.  

I guess it would require stepping through all the initial sync events, which would be quite a task.  I'm guessing that your account is in a lot of rooms.

I notice that you appear to be running your own Matrix server.  That might have something to do with it, because I've never encountered this bug on matrix.org.  It could still indicate a bug in this client, but it's hard to say without doing a lot of digging.  What Matrix server are you running, what version, etc?

**Comment by seanfarley** [comment] 2020-06-15 19:21
I'm using the ansible docker setup from here:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook.md

I'm still just learning about matrix so this is my first time setting it up (currently, we're still at the point where I wouldn't lose much if I had to start over). I haven't done too much customization besides just basic bridging stuff.

`Homeserver version: Synapse 1.14.0`

**Comment by alphapapa** [comment] 2020-06-17 03:01
Unfortunately, that doesn't give me anything to go on.  Since I can't reproduce this, I'm afraid you will have to debug it yourself.

Since you have your own server, I'd suggest trying to make a test account to reproduce it with a minimal number of joined rooms and state events, etc.  If that's not possible, then I guess you'll have to follow the processing of all of the initial sync's state events and look for clues.  Edebug might help, but it will probably require reading the debug logs (see the `matrix-log` option).

**Comment by seanfarley** [comment] 2020-06-17 05:27
No worries; I'll just live with this for now since I'm still dabbling with matrix. If I find anything, I'll report back here :-)

**Comment by seanfarley** [comment] 2021-02-21 18:16
I was able to fix this by protecting a few function calls from operating on killed buffers. I'm not even sure why they are there but I'd be happy to make a PR if that's acceptable. FWIW, I found that all the busted logic was from my IRC bridge which randomly disconnects me; meaning: so on my matrix client, I have a `#bitbucket` room but in actuality that room won't receive messages / isn't actually connected until I send a message first.

**Comment by hugoroy** [comment] 2021-08-20 12:46
Hello here
I installed matrix-client through doom-emacs' "straight" package manager.
When trying to connect: I got

```
Jacked in to matrix.fdn.fr.  Syncing...
error in process filter: matrix-client--delete-event: Wrong type argument: (or eieio-object class), (matrix-room-client-data), obj
error in process filter: Wrong type argument: (or eieio-object class), (matrix-room-client-data), obj
Quit
```

**Comment by alphapapa** [comment] 2021-08-20 13:29
@hugoroy  This package is not being actively developed.  Please see https://github.com/alphapapa/ement.el

**Comment by alphapapa** [comment] 2023-03-14 10:23
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.

**Closed by alphapapa** 2023-03-14 10:23 UTC
